# -*- coding: utf-8 -*-
"""yfinance_US_stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9X-zuQFRVnL0X5Mr03f5-RKNBpHAEhk
"""

import requests
import pandas as pd

url = 'https://www.slickcharts.com/sp500'
headers = {"User-Agent" : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'}

request = requests.get(url, headers = headers)

data = pd.read_html(request.text)[0]

# 欄位『Symbol』就是股票代碼
stk_list = data.Symbol

# 用 replace 將符號進行替換
stk_list = data.Symbol.apply(lambda x: x.replace('.', '-'))
stk_list

data = pd.read_html(request.text)[0]
data

!pip install yfinance

import yfinance as yf
import time

# 先測試一檔試看看
stock = yf.Ticker('AAPL')

# 取得價量資料＋股利發放資料＋股票分割資料
stock.history(period = 'max')

# 創立一個紀錄失敗股票的 list
failed_list = []

# 開始迴圈抓資料囉！
for i in stk_list[0:10]:  # 要下載全部就把[0:10]拿掉
    try :
        # 打印出目前進度
        print('processing: ' + i)
        # 填入股票代碼後直接下載成 csv 格式
        stock = yf.Ticker(i)
        stock.history(period = 'max').to_csv('price_'+i+'.csv')
        # 停一秒，再抓下一檔，避免對伺服器造成負擔而被鎖住
        time.sleep(1)
    except :
        failed_list.append(i)
        continue

! ls

from google.colab import files
# 把資料下載到本機端的方法
files.download("price_AAPL.csv")

